import sys

try:
    xyz
except NameError as e:
    sys.print_exception(e)
